spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  activemq:
    broker-url: tcp://${ACTIVE_MQ_HOST}:${ACTIVE_MQ_PORT}
    user: ${ACTIVE_MQ_USER}
    password: ${ACTIVE_MQ_PASSWORD}
  flyway:
    enabled: false
    validate-on-migrate: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    properties:
      hibernate:
        show_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    path: /swagger-ui.html
    enabled: false
jms:
  request-queue: dev.cbr.request
  response-queue: dev.cbr.response
server:
  port: 8081