spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/currency_db
    username: postgres
    password: postgres
  activemq:
    broker-url: tcp://localhost:61617
    user: admin
    password: admin
  flyway:
    enabled: true
    validate-on-migrate: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    properties:
      hibernate:
        show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
jms:
  request-queue: dev.cbr.request
  response-queue: dev.cbr.response
server:
  port: 8081